import os, time, logging
from knowledge_base import KnowledgeBase

class SelfCodeGenerator:
    def __init__(self, knowledge_base: KnowledgeBase, out_dir: str = "generated"):
        self.kb = knowledge_base
        self.out_dir = out_dir
        os.makedirs(self.out_dir, exist_ok=True)

    def generate_python_module(self, module_name: str, code_content: str) -> str:
        filename = f"{module_name}.py"
        path = os.path.join(self.out_dir, filename)
        with open(path, "w", encoding="utf-8") as f:
            f.write("# Auto-generated by SelfCodeGenerator\n")
            f.write("# timestamp: {}\n".format(time.time()))
            f.write(code_content + "\n")
        logging.info("Generated python module: %s", path)
        self.kb.add_knowledge(f"generated:{module_name}", {"path": path, "created": time.time()})
        return path

    def generate_simple_web(self, name: str, html: str, js: str = "", css: str = "") -> str:
        base = os.path.join(self.out_dir, name)
        os.makedirs(base, exist_ok=True)
        html_path = os.path.join(base, "index.html")
        with open(html_path, "w", encoding="utf-8") as f:
            f.write("<!-- Generated HTML -->\n" + html)
        if js:
            with open(os.path.join(base, "script.js"), "w", encoding="utf-8") as f:
                f.write(js)
        if css:
            with open(os.path.join(base, "style.css"), "w", encoding="utf-8") as f:
                f.write(css)
        self.kb.add_knowledge(f"generated:web:{name}", {"path": html_path, "created": time.time()})
        logging.info("Generated web bundle: %s", base)
        return base
